# Generated by Django 5.2.8 on 2025-11-16 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=500, null=True)),
            ],
            options={
                'db_table': 'SGR_P_Categoria',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(db_column='IdCiudad', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=100)),
            ],
            options={
                'db_table': 'SGR_P_Ciudad',
            },
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id_ingrediente', models.AutoField(db_column='IdIngrediente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
            ],
            options={
                'db_table': 'SGR_P_Ingrediente',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.AutoField(db_column='IdReceta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('proceso', models.TextField(blank=True, db_column='Proceso', null=True)),
            ],
            options={
                'db_table': 'SGR_M_Receta',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id_restaurante', models.AutoField(db_column='IdRestaurante', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=255, null=True)),
            ],
            options={
                'db_table': 'SGR_M_Restaurante',
            },
        ),
        migrations.CreateModel(
            name='TipoMenu',
            fields=[
                ('id_tipo_menu', models.AutoField(db_column='IdTipoMenu', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(db_column='Descripcion', max_length=255)),
            ],
            options={
                'db_table': 'SGR_P_TipoMenu',
            },
        ),
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id_chef', models.AutoField(db_column='IdChef', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('cedula', models.CharField(db_column='Cedula', max_length=20)),
                ('turno', models.CharField(blank=True, db_column='Turno', max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('sexo', models.CharField(blank=True, db_column='Sexo', max_length=1, null=True)),
                ('ciudad', models.ForeignKey(blank=True, db_column='IdCiudad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crearMenu.ciudad')),
            ],
            options={
                'db_table': 'SGR_M_Chef',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(db_column='IdMenu', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('chef', models.ForeignKey(blank=True, db_column='IdChef', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crearMenu.chef')),
                ('restaurante', models.ForeignKey(db_column='IdRestaurante', on_delete=django.db.models.deletion.CASCADE, to='crearMenu.restaurante')),
                ('tipo_menu', models.ForeignKey(blank=True, db_column='IdTipoMenu', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crearMenu.tipomenu')),
            ],
            options={
                'db_table': 'SGR_M_Menu',
            },
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id_plato', models.AutoField(db_column='IdPlato', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=255)),
                ('categoria', models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crearMenu.categoria')),
                ('receta', models.ForeignKey(blank=True, db_column='IdReceta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='crearMenu.receta')),
            ],
            options={
                'db_table': 'SGR_M_Plato',
            },
        ),
        migrations.CreateModel(
            name='DetalleNutricional',
            fields=[
                ('id_detalle_nutricional', models.AutoField(db_column='IdDetalleNutricional', primary_key=True, serialize=False)),
                ('carbohidratos', models.DecimalField(blank=True, db_column='Carbohidratos', decimal_places=2, max_digits=10, null=True)),
                ('proteina', models.DecimalField(blank=True, db_column='Proteina', decimal_places=2, max_digits=10, null=True)),
                ('caloria', models.DecimalField(blank=True, db_column='Caloria', decimal_places=2, max_digits=10, null=True)),
                ('grasa', models.DecimalField(blank=True, db_column='Grasa', decimal_places=2, max_digits=10, null=True)),
                ('plato', models.OneToOneField(db_column='IdPlato', on_delete=django.db.models.deletion.CASCADE, to='crearMenu.plato')),
            ],
            options={
                'db_table': 'SGR_T_DetalleNutricional',
            },
        ),
        migrations.CreateModel(
            name='DetalleMenu',
            fields=[
                ('id_detalle_menu', models.AutoField(db_column='IdDetalleMenu', primary_key=True, serialize=False)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('menu', models.ForeignKey(db_column='IdMenu', on_delete=django.db.models.deletion.CASCADE, to='crearMenu.menu')),
                ('plato', models.ForeignKey(db_column='IdPlato', on_delete=django.db.models.deletion.CASCADE, to='crearMenu.plato')),
            ],
            options={
                'db_table': 'SGR_T_DetalleMenu',
            },
        ),
        migrations.CreateModel(
            name='DetalleIngrediente',
            fields=[
                ('id_detalle_ingrediente', models.AutoField(db_column='IdDetalleIngrediente', primary_key=True, serialize=False)),
                ('cantidad', models.DecimalField(db_column='Cantidad', decimal_places=2, max_digits=10)),
                ('ingrediente', models.ForeignKey(db_column='IdIngrediente', on_delete=django.db.models.deletion.CASCADE, to='crearMenu.ingrediente')),
                ('receta', models.ForeignKey(db_column='IdReceta', on_delete=django.db.models.deletion.CASCADE, to='crearMenu.receta')),
            ],
            options={
                'db_table': 'SGR_T_DetalleIngrediente',
            },
        ),
    ]
