from django.urls import path
from . import views

app_name = 'crearMenu'

urlpatterns = [
    path('', views.PaginaCrearMenu.as_view(), name='crear_menu'),
    path('menu/<int:menu_id>/detalle/', views.gestionar_detalle_menu,
         name='gestionar_detalle_menu'),
    path('menu/eliminar/<int:menu_id>/',
         views.eliminar_menu, name='eliminar_menu'),
    path('menu/<int:menu_id>/imprimir/',
         views.imprimir_menu_pdf, name='imprimir_menu_pdf'),
    path('reportes/', views.dashboard_reportes, name='reportes'),
    path('detalle/eliminar/<int:detalle_id>/',
         views.eliminar_detalle_menu, name='eliminar_detalle'),
    path('crear-categoria/', views.crear_categoria, name='crear_categoria'),
    path('crear-plato/', views.crear_plato, name='crear_plato'),
    path('platos/', views.lista_platos, name='lista_platos'),
    path('platos/editar/<int:plato_id>/',
         views.editar_plato, name='editar_plato'),
    path('ingredientes/', views.lista_ingredientes, name='lista_ingredientes'),
    path('ingredientes/eliminar/<int:ingrediente_id>/',
         views.eliminar_ingrediente, name='eliminar_ingrediente'),
    path('recetas/', views.lista_recetas, name='lista_recetas'),
    path('recetas/crear/', views.crear_receta, name='crear_receta'),
    path('recetas/<int:receta_id>/gestionar/',
         views.gestionar_receta, name='gestionar_receta'),
    path('recetas/detalle/eliminar/<int:detalle_id>/',
         views.eliminar_detalle_ingrediente, name='eliminar_detalle_ingrediente'),
    path('chefs/', views.lista_chefs, name='lista_chefs'),
    path('chefs/crear/', views.crear_chef, name='crear_chef'),
    path('chefs/eliminar/<int:chef_id>/',
         views.eliminar_chef, name='eliminar_chef'),
    path('ciudades/', views.lista_ciudades, name='lista_ciudades'),
    path('ciudades/eliminar/<int:ciudad_id>/',
         views.eliminar_ciudad, name='eliminar_ciudad'),
    path('tipos-menu/', views.lista_tipos_menu, name='lista_tipos_menu'),
    path('tipos-menu/eliminar/<int:tipo_id>/',
         views.eliminar_tipo_menu, name='eliminar_tipo_menu'),
    path('restaurantes/', views.lista_restaurantes, name='lista_restaurantes'),
    path('restaurantes/eliminar/<int:restaurante_id>/',
         views.eliminar_restaurante, name='eliminar_restaurante'),
]
